#!/usr/bin/env bash

shopt -s extglob

# Don't let this stuff get in; Remove it if it gets in.
git rm -r __pycache__

# What's the correct way to do this?
git rm -r .ipynb_checkpoints
git rm -r ./*/.ipynb_checkpoints
git rm -r ./*/*/.ipynb_checkpoints
git rm -r ./*/*/*/.ipynb_checkpoints
git rm -r ./*/*/*/*/.ipynb_checkpoints
git rm -r ./*/*/*/*/*/.ipynb_checkpoints
git rm -r ./*/*/*/*/*/*/.ipynb_checkpoints
rm -r .ipynb_checkpoints
rm -r ./*/.ipynb_checkpoints
rm -r ./*/*/.ipynb_checkpoints
rm -r ./*/*/*/.ipynb_checkpoints
rm -r ./*/*/*/*/.ipynb_checkpoints
rm -r ./*/*/*/*/*/.ipynb_checkpoints
rm -r ./*/*/*/*/*/*/.ipynb_checkpoints

# Clean up editor files
find . -iname "*~" -exec rm {} \;

echo running autodoc
cd ./docs
sphinx-apidoc -fe -o . ../
#make clean
make html
cd ../

git add .
git commit -m "rebuilt documentation"

